background {
    monitor = 
    path = ~/.config/hypr/hyprlock/blue_tempest.png
    blur_passes = 4
    blur_size = 1
}

general {
    hide_cursor = false
    disable_loading_bar = true
}

input-field {
    monitor = DP-1
    size = 250, 40
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.4
    dots_center = true
    outer_color = rgba(0b294222)
    inner_color = rgba(0b2942aa)
    font_color = rgb(eeeeee)
    fade_on_empty = false
    rounding = 6
    check_color = rgba(0b294222)
    fail_color = rgb(fc514e)
    font_family = JetBrains Mono
    placeholder_text = <i><span foreground="##b2ceee">Password</span></i>
    fail_text = <i><span foreground="##fc514e">Wrong password!</span></i>
    position = 0, 0
    halign = center
    valign = center
}

label {
    monitor = DP-1
    text = cmd[update:1000] echo "$(date +"%a %b %d")"
    color = rgb(eeeeee)
    font_size = 22
    font_family = JetBrains Mono
    position = 0, 300
    halign = center
    valign = center
}

label {
    monitor = DP-1
    text = cmd[update:100] echo "$(date +"%I:%M %p")"
    color = rgb(eeeeee)
    font_size = 60
    font_family = JetBrains Mono Bold
    position = 0, 200
    halign = center
    valign = center
}

