-- Environment variables

-- hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
-- hl.env("XDG_SESSION_TYPE", "wayland")
-- hl.env("XDG_SESSION_DESKTOP", "Hyprland")
--
-- hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
--
-- hl.env("GDK_BACKEND", "wayland,x11,*")
--
-- hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
-- hl.env("QT_QPA_PLATFORM", "wayland;xcb")
