plugin {
    dynamic-cursors {
        enabled = true
        mode = none

        shake {
            enabled = true
            nearest = false
            threshold = 8.0
            base = 2.0
            speed = 4.0
            influence = 0.0
            limit = 3.0
            timeout = 1000
            effects = false
            ipc = false
        }
    }

    split-monitor-workspaces {
        count = 9
        keep_focused = 1
        enable_notifications = 0
        enable_persistent_workspaces = 1
    }
}

exec-once = hyprpm reload -nn
