#   _____                              _   _____ _____ 
#  |_   _|                            | | |  _  /  ___|
#    | | ___ _ __ ___  _ __   ___  ___| |_| | | \ `--. 
#    | |/ _ \ '_ ` _ \| '_ \ / _ \/ __| __| | | |`--. \
#    | |  __/ | | | | | |_) |  __/\__ \ |_\ \_/ /\__/ /
#    \_/\___|_| |_| |_| .__/ \___||___/\__|\___/\____/ 
#                     | |                              
#                     |_|                              
#                                                      
# TempestOS Alacritty config

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#7c8f8f"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#21c7a8"
magenta = "#ae81ff"
red = "#ff5874"
white = "#d6deeb"
yellow = "#ecc48d"

[colors.cursor]
cursor = "#9ca1aa"
text = "#080808"

[colors.normal]
black = "#1d3b53"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#a1cd5e"
magenta = "#c792ea"
red = "#fc514e"
white = "#a1aab8"
yellow = "#e3d18a"

[colors.primary]
background = "#011627"
bright_foreground = "#eeeeee"
foreground = "#bdc1c6"

[colors.selection]
background = "#b2ceee"
text = "#080808"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 500

[window]
opacity = 1.0
