[colors]
draw_bold_text_with_bright_colors = true

# Default colors
[colors.primary]
background = "#011627"
foreground = "#d6deeb"

# Cursor colors
[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "#22da6e"

# Search colors
[colors.search.matches]
foreground = "#000000"
background = "#22da6e"

[colors.search.focused_match]
foreground = "#ffffff"
background = "#22da6e"

[colors.footer_bar]
foreground = "#ffffff"
background = "#1d3b53"

# Selection colors
[colors.selection]
text = "#ffffff"
background = "#0d486e"

# Normal colors
[colors.normal]
black = "#011627"
red = "#EF5350"
green = "#22da6e"
yellow = "#c5e478"
blue = "#82AAFF"
magenta = "#C792EA"
cyan = "#21c7a8"
white = "#ffffff"

# Bright colors
[colors.bright]
black = "#575656"
red = "#EF5350"
green = "#22da6e"
yellow = "#ffeb95"
blue = "#82AAFF"
magenta = "#C792EA"
cyan = "#7fdbca"
white = "#ffffff"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[scrolling]
history = 500

[window]
opacity = 1.0

[window.padding]
x = 4
y = 4
